In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
import os
print(os.listdir(r'C:\Users\HEY\E-commerce'))
df=pd.read_excel(r'C:\Users\HEY\E-commerce\Superstore.xlsx')

['Superstore.xlsx']

In [25]:
df.head()

,Order_ID,Order_Date,Customer_Name,Region,Category,Sub_Category,Sales,Quantity,Profit
0,1001,2025-06-08,Anjali,West,Electronics,Mouse,56522,1,2826
1,1002,2025-09-23,Pooja,South,Office Supplies,Marker,7513,3,1126
2,1003,2025-10-01,Karthik,South,Electronics,Mouse,29569,7,5618
3,1004,2025-12-25,Ramesh,South,Electronics,SSD,33802,9,3042
4,1005,2025-08-10,Asha,North,Office Supplies,Stapler,7362,9,1325

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   int64
 1   Order_Date     1000 non-null   object
 2   Customer_Name  1000 non-null   object
 3   Region         1000 non-null   object
 4   Category       1000 non-null   object
 5   Sub_Category   1000 non-null   object
 6   Sales          1000 non-null   int64
 7   Quantity       1000 non-null   int64
 8   Profit         1000 non-null   int64
dtypes: int64(4), object(5)
memory usage: 70.4+ KB

In [27]:
df.describe()

          Order_ID         Sales     Quantity        Profit
count  1000.000000   1000.000000  1000.000000   1000.000000
mean   1500.500000  18261.055000     5.441000   2320.761000
std     288.819436  15616.532456     2.845455   2266.594991
min    1001.000000    228.000000     1.000000     13.000000
25%    1250.750000   5756.500000     3.000000    587.000000
50%    1500.500000  12250.000000     5.000000   1450.500000
75%    1750.250000  29142.250000     8.000000   3530.750000
max    2000.000000  59858.000000    10.000000  11669.000000

In [28]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
Region           0
Category         0
Sub_Category     0
Sales            0
Quantity         0
Profit           0
dtype: int64

In [29]:
df.drop_duplicates(inplace=True)

In [31]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [33]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month_name()

In [34]:
df.groupby("Category")["Sales"].sum()

Category
Electronics        10711141
Furniture           5842783
Office Supplies     1707131
Name: Sales, dtype: int64

In [36]:
df.groupby("Customer_Name")["Sales"].sum().sort_values(ascending=False)

Customer_Name
Nisha      918773
Vinod      890291
Ajay       878798
Deepa      860844
Arun       834174
Sanjay     806860
Priya      785295
Naveen     744928
Swathi     712236
Ramesh     668406
Manoj      625755
Kavya      608339
Prakash    600877
Asha       592120
Vijay      591461
Gokul      590039
Pooja      587619
Sneha      558756
Anjali     558235
Divya      553611
Suresh     539896
Latha      477395
Karthik    473494
Rahul      434763
Amit       414796
Meena      410520
Reshma     408194
Renu       407792
Keerthi    365131
Harish     361657
Name: Sales, dtype: int64

In [37]:
df.groupby("Month")["Sales"].sum()

Month
April        1605547
August       1494303
December     1978584
February     1311375
January      1388538
July         1257081
June         1282970
March        1829204
May          1353751
November     1410653
October      1716150
September    1632899
Name: Sales, dtype: int64

In [38]:
df.groupby("Region")["Sales"].sum()

Region
East     4212705
North    4895611
South    4706726
West     4446013
Name: Sales, dtype: int64

In [39]:
df.groupby("Category")["Profit"].sum()

Category
Electronics        1376182
Furniture           732970
Office Supplies     211609
Name: Profit, dtype: int64

In [40]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [41]:
df.to_excel("clean_superstore.xlsx", index=False)

In [42]:
df.to_csv("superstore.csv", index=False, encoding='utf-8')

In [43]:
df.to_csv("superstore.csv", index=False, encoding='utf-8-sig')

In [44]:
import os
print(os.getcwd())

C:\Users\HEY